# Generated by Django 5.0.2 on 2024-02-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=20),
        ),
    ]
